[package]
name = "sage"
version = "0.1.0"
authors = ["Victor I. Afolabi <javafolabi@gmail.com>"]
edition = "2018"

[lib]
name = "sage"

[dependencies]
dotenv = "0.14"
log = "0.4"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }